export type SupportedLocale = 'en' | 'tr';

export const defaultLocale: SupportedLocale = 'tr';

const copyByLocale = {
	en: {
		account: {
			authErrorTitle: 'Account issue',
			clearLocalToken: 'Clear local token',
			description: 'Profile, basic session details, and sign-out stay here.',
			heading: 'Account',
			logout: 'Sign out',
			profileSection: 'Account summary',
			refreshAuthContext: 'Refresh account state',
		},
		approval: {
			action: 'Action',
			approve: 'Approve',
			approved: 'Approved',
			callId: 'Call id',
			cancelled: 'Cancelled',
			details: 'Technical details',
			expired: 'Expired',
			note: 'Note',
			pending: 'Pending approval',
			pendingEmphasis: 'Runa paused here and is waiting for your decision before continuing.',
			reject: 'Reject',
			rejected: 'Rejected',
			tool: 'Tool',
		},
		appNav: {
			accountDescription: 'Profile, session, and sign-out.',
			accountLabel: 'Account',
			chatDescription: 'Conversation, current run, and approvals.',
			chatLabel: 'Chat',
			devicesDescription: 'Connected desktop companions.',
			devicesLabel: 'Devices',
			developerLabel: 'Developer Mode',
			historyDescription: 'Saved conversations and shared work.',
			historyLabel: 'History',
			notificationsDescription: 'Alerts, approvals, and reminders.',
			notificationsLabel: 'Notifications',
			navLabel: 'Authenticated app navigation',
		},
		appShell: {
			authenticatedSession: 'Authenticated session',
			chatEyebrow: 'work companion',
			chatSubtitle: 'The main surface is the chat workspace.',
			chatTitle: 'Chat workspace',
			developerEyebrow: 'second layer',
			developerSubtitle: 'Developer-only configuration and debug visibility live here.',
			developerTitle: 'Developer Mode',
			devicesEyebrow: 'connected devices',
			devicesSubtitle:
				'Desktop companion presence and allowed capabilities live in their own space.',
			devicesTitle: 'Devices',
			historyEyebrow: 'work history',
			historySubtitle: 'Past conversations stay searchable without crowding the main chat.',
			historyTitle: 'History',
			notificationsEyebrow: 'notifications',
			notificationsSubtitle: 'Approvals, updates, and reminders stay together here.',
			notificationsTitle: 'Notifications',
			serviceSession: 'Service session',
			accountEyebrow: 'account',
			accountSubtitle: 'Only the essential account and session controls stay here.',
			accountTitle: 'Account',
		},
		auth: {
			authenticatedShellNotice:
				'A successful sign-in opens the authenticated workspace immediately.',
			bearerTokenRequired: 'Bearer token is required.',
			bootstrapDescription:
				'The app checks auth state on load, reads OAuth redirect tokens, and decides whether to open login or the authenticated workspace.',
			bootstrapTitle: 'Current browser auth state',
			clearStoredToken: 'Clear stored token',
			clearStoredTokenNotice:
				'The stored bearer token was cleared only in this browser tab. A remote session may still remain active until the current access token expires.',
			connecting: 'Checking account state',
			continueWithGithub: 'Continue with GitHub',
			continueWithGoogle: 'Continue with Google',
			devSession: 'Start local dev session',
			email: 'Email address',
			invalidSession: 'Bearer token did not resolve to an authenticated session.',
			localDevOnly: 'Local dev auth bootstrap can only start in the browser.',
			login: 'Sign in',
			loginAction: 'Sign in',
			loginDescription: 'Sign in with your email and password.',
			loginPending: 'Signing in...',
			logoutRemoteWarning:
				'Local browser state was cleared, but the remote session may remain active until the current access token expires.',
			modeLabel: 'Authentication mode',
			noStoredToken: 'No stored token in this tab',
			oauthDescription:
				'This starts a real OAuth flow. The app reads the returned token during auth bootstrap.',
			oauthRedirecting: 'Redirecting to the OAuth provider...',
			oauthValidating: 'OAuth returned to the app. Validating the session now.',
			password: 'Password',
			passwordPlaceholderLogin: 'Enter your password',
			passwordPlaceholderSignup: 'Create a strong password',
			profileDeferred: 'Account management remains intentionally lightweight in this sprint.',
			refreshAuthContext: 'Refresh auth state',
			signup: 'Create account',
			signupAction: 'Create account',
			signupDescription: 'Create an account with email and password.',
			signupPending: 'Creating account...',
			signupVerificationNote:
				'If email confirmation is enabled, the app stays on the login surface and shows the verification message.',
			startingDevSession: 'Starting a local dev auth session...',
			statusAnonymous: 'Anonymous',
			statusBootstrapping: 'Checking auth context',
			storedToken: 'Stored token in this tab',
			subtitle: 'Runa opens first as a simple work companion. Technical auth seams stay secondary.',
			title: 'Continue with Runa',
			token: 'Token',
			tokenAction: 'Validate token',
			tokenDescription: 'Validate an existing bearer token.',
			tokenFallbackNote:
				'The token path stays available as a fallback for existing sessions and troubleshooting.',
			tokenPending: 'Validating...',
			tokenPlaceholder: 'Paste a bearer token',
			unresolvedPrincipal: 'Unresolved',
		},
		chat: {
			composerPlaceholder: 'Write what you want to get done...',
			configMissing:
				'Chat is ready, but runtime configuration is incomplete. Open Developer Mode and enter a valid API key before sending a request.',
			currentRunHeading: 'Current work',
			emptySurface:
				'No visible work yet. Send a message to start and see the current work surface here.',
			heroSubtitle:
				'Conversation, approvals, and the live work surface stay together here. Technical controls live in Developer Mode.',
			heroTitle: 'Your work companion',
			openDeveloper: 'Open Developer Mode',
			runConnectionClosed: 'Connection closed',
			runConnectionConnecting: 'Connecting',
			runConnectionOpen: 'Live',
			send: 'Send',
			sending: 'Sending...',
			submitConnectionConnecting: 'Connecting...',
			submitConnectionWaiting: 'Waiting for live connection',
			submitInProgress: 'Working...',
		},
		developer: {
			apiKey: 'API key',
			configDescription:
				'These settings feed the live chat runtime but stay out of the main chat surface.',
			configHeading: 'Runtime configuration',
			currentDefaults: 'Current defaults',
			description:
				'Developer-only runtime controls, raw transport visibility, and troubleshooting live here.',
			heading: 'Developer Mode',
			includePresentationBlocks: 'Request presentation blocks',
			lastError: 'Latest runtime error',
			model: 'Model',
			noMessages: 'No transport messages yet.',
			provider: 'Provider',
			rawTransport: 'Raw transport',
			refreshAuthContext: 'Refresh auth state',
			showTransport: 'Show transport',
			hideTransport: 'Hide transport',
			localOnlyNote: 'These settings are local to this browser and exist for dev or operator use.',
			clearLocalToken: 'Clear local token',
			scope: 'Scope',
			claims: 'Claims',
			userMetadata: 'User metadata',
			troubleshooting: 'Troubleshooting',
		},
		run: {
			approvalBoundary: 'Approval boundary',
			currentRunProgress: 'Current work',
			currentSurfaceContext: 'Context',
			observedSteps: 'Recent steps',
			runtimePhases: 'Work phases',
			showingLatestSteps: 'Son {count} adÄ±m gÃ¶steriliyor',
			pastRuns: 'Recent work',
			pastRunsCollapsed: 'Recent work stays available without crowding the main conversation.',
			surfaceHeading: 'Current work surface',
			surfaceSubtitle: 'The latest summaries and details stay here while the work continues.',
		},
		runtime: {
			apiKeyRequired: 'API key is required.',
			connectionOpening: 'Live connection is still opening. Wait a moment and try again.',
			connectionUnavailable:
				'Live connection is not ready yet. Wait for reconnection before sending a request.',
			modelRequired: 'Model is required.',
			promptRequired: 'Prompt is required.',
			unsupportedWsMessage: 'Unsupported WebSocket server message.',
			wsClosedRetrying: 'Live connection closed. Retrying...',
			wsFailedRetrying: 'WebSocket connection failed. Retrying...',
			wsNotOpen: 'WebSocket is not open.',
			wsParsingUnknown: 'Unknown WebSocket message parsing error.',
			unknownApprovalSubmit: 'Unknown approval resolve submit error.',
			unknownInspectionSubmit: 'Unknown inspection request submit error.',
			unknownSubmit: 'Unknown submit error.',
		},
	},
	tr: {
		account: {
			authErrorTitle: 'Hesap sorunu',
			clearLocalToken: 'KaydÄ± temizle',
			description: 'Profilini, oturumunu ve tercihlerini yÃ¶net.',
			heading: 'Hesap',
			logout: 'Ã‡Ä±kÄ±ÅŸ yap',
			profileSection: 'Hesap Ã¶zeti',
			refreshAuthContext: 'Hesap durumunu yenile',
		},
		approval: {
			action: 'Ä°ÅŸlem',
			approve: 'Onayla',
			approved: 'OnaylandÄ±',
			callId: 'Ä°stek kimliÄŸi',
			cancelled: 'VazgeÃ§ildi',
			details: 'AyrÄ±ntÄ±lar',
			expired: 'SÃ¼re doldu',
			note: 'Not',
			pending: 'Onay bekliyor',
			pendingEmphasis: 'Runa devam etmeden Ã¶nce kararÄ±nÄ± bekliyor.',
			reject: 'Reddet',
			rejected: 'Reddedildi',
			tool: 'AraÃ§',
		},
		appNav: {
			accountDescription: 'Profil ve tercihler.',
			accountLabel: 'Hesap',
			chatDescription: 'Sohbet ve onaylar.',
			chatLabel: 'Sohbet',
			devicesDescription: 'BaÄŸlÄ± bilgisayarlar.',
			devicesLabel: 'Cihazlar',
			developerLabel: 'GeliÅŸtirici',
			historyDescription: 'KayÄ±tlÄ± sohbetler.',
			historyLabel: 'GeÃ§miÅŸ',
			notificationsDescription: 'Onaylar, hatirlatmalar ve guncellemeler.',
			notificationsLabel: 'Bildirimler',
			navLabel: 'Uygulama gezintisi',
		},
		appShell: {
			authenticatedSession: 'AÃ§Ä±k oturum',
			chatEyebrow: 'Ã§alÄ±ÅŸma ortaÄŸÄ±',
			chatSubtitle: 'Ä°ÅŸi sohbet iÃ§inde ilerlet.',
			chatTitle: 'Ã‡alÄ±ÅŸma alanÄ±',
			developerEyebrow: 'geliÅŸtirici',
			developerSubtitle: 'GeliÅŸtirici ayarlarÄ± ve tanÄ±lama araÃ§larÄ±.',
			developerTitle: 'GeliÅŸtirici',
			devicesEyebrow: 'baÄŸlÄ± cihazlar',
			devicesSubtitle: 'Bilgisayar baÄŸlantÄ±larÄ±nÄ± ve izinleri yÃ¶net.',
			devicesTitle: 'Cihazlar',
			historyEyebrow: 'Ã§alÄ±ÅŸma geÃ§miÅŸi',
			historySubtitle: 'Eski sohbetlere ve yarÄ±m kalan iÅŸlere dÃ¶n.',
			historyTitle: 'GeÃ§miÅŸ',
			notificationsEyebrow: 'bildirimler',
			notificationsSubtitle: 'Onaylarini, guncellemeleri ve ertelediklerini yonet.',
			notificationsTitle: 'Bildirimler',
			serviceSession: 'Servis oturumu',
			accountEyebrow: 'hesap',
			accountSubtitle: 'Profilini ve tercihlerini yÃ¶net.',
			accountTitle: 'Hesap',
		},
		auth: {
			authenticatedShellNotice: 'GiriÅŸ tamamlandÄ±. Ã‡alÄ±ÅŸma alanÄ±n aÃ§Ä±lÄ±yor.',
			bearerTokenRequired: 'Oturum anahtarÄ± gerekli.',
			bootstrapDescription: 'Runa, giriÅŸ durumunu kontrol edip seni doÄŸru ekrana yÃ¶nlendirir.',
			bootstrapTitle: 'GiriÅŸ durumu',
			clearStoredToken: 'KayÄ±tlÄ± giriÅŸi temizle',
			clearStoredTokenNotice:
				'Bu tarayÄ±cÄ±daki kayÄ±t temizlendi. Uzak oturum kÄ±sa sÃ¼re daha aÃ§Ä±k kalabilir.',
			connecting: 'GiriÅŸ hazÄ±rlanÄ±yor',
			continueWithGithub: 'GitHub ile devam et',
			continueWithGoogle: 'Google ile devam et',
			devSession: 'Yerel deneme oturumu baÅŸlat',
			email: 'E-posta adresi',
			invalidSession: 'Bu giriÅŸ geÃ§erli bir oturuma dÃ¶nÃ¼ÅŸmedi.',
			localDevOnly: 'Yerel deneme oturumu yalnÄ±z tarayÄ±cÄ±da baÅŸlatÄ±labilir.',
			login: 'GiriÅŸ',
			loginAction: 'GiriÅŸ yap',
			loginDescription: 'E-posta ve ÅŸifre ile giriÅŸ yap.',
			loginPending: 'GiriÅŸ yapÄ±lÄ±yor...',
			logoutRemoteWarning:
				'Bu tarayÄ±cÄ±daki kayÄ±t temizlendi, uzak oturum kÄ±sa sÃ¼re daha aÃ§Ä±k kalabilir.',
			modeLabel: 'Kimlik doÄŸrulama modu',
			noStoredToken: 'Bu sekmede kayÄ±tlÄ± giriÅŸ yok',
			oauthDescription: 'Google veya GitHub ile devam edebilirsin.',
			oauthRedirecting: 'GiriÅŸ saÄŸlayÄ±cÄ±sÄ±na yÃ¶nlendiriliyor...',
			oauthValidating: 'GiriÅŸ bilgilerin doÄŸrulanÄ±yor.',
			password: 'Åifre',
			passwordPlaceholderLogin: 'Åifreni gir',
			passwordPlaceholderSignup: 'GÃ¼Ã§lÃ¼ bir ÅŸifre oluÅŸtur',
			profileDeferred: 'Hesap yÃ¶netimi sade tutuldu.',
			refreshAuthContext: 'GiriÅŸ durumunu yenile',
			signup: 'KayÄ±t ol',
			signupAction: 'Hesap oluÅŸtur',
			signupDescription: 'E-posta ve ÅŸifre ile hesap oluÅŸtur.',
			signupPending: 'Hesap oluÅŸturuluyor...',
			signupVerificationNote:
				'E-posta doÄŸrulamasÄ± gerekiyorsa giriÅŸ ekranÄ±nda bir doÄŸrulama mesajÄ± gÃ¶rÃ¼rsÃ¼n.',
			startingDevSession: 'Yerel deneme oturumu baÅŸlatÄ±lÄ±yor...',
			statusAnonymous: 'GiriÅŸ yap',
			statusBootstrapping: 'GiriÅŸ hazÄ±rlanÄ±yor',
			storedToken: 'Bu sekmede kayÄ±tlÄ± giriÅŸ var',
			subtitle: 'Projeni bilen sakin bir Ã§alÄ±ÅŸma ortaÄŸÄ±na giriÅŸ yap.',
			title: 'Runa ile devam et',
			token: 'Oturum anahtarÄ±',
			tokenAction: 'GiriÅŸi doÄŸrula',
			tokenDescription: 'Var olan bir oturum anahtarÄ±nÄ± doÄŸrula.',
			tokenFallbackNote: 'Bu yol yalnÄ±z mevcut oturumu kurtarmak iÃ§in kullanÄ±lÄ±r.',
			tokenPending: 'DoÄŸrulanÄ±yor...',
			tokenPlaceholder: 'Oturum anahtarÄ±nÄ± yapÄ±ÅŸtÄ±r',
			unresolvedPrincipal: 'Ã‡Ã¶zÃ¼lmedi',
		},
		chat: {
			composerPlaceholder: 'Ne yapmak istediÄŸini yaz...',
			configMissing: 'Sohbet ÅŸu anda hazÄ±r deÄŸil. Biraz sonra yeniden deneyebilirsin.',
			currentRunHeading: 'Mevcut Ã§alÄ±ÅŸma',
			emptySurface: 'HazÄ±rsan ilk mesajÄ± yaz; Runa iÅŸi adÄ±m adÄ±m toparlasÄ±n.',
			heroSubtitle: 'Ä°ÅŸi sohbet iÃ§inde ilerlet; onay gereken adÄ±mlarda karar sende kalÄ±r.',
			heroTitle: 'Ã‡alÄ±ÅŸma ortaÄŸÄ±n',
			openDeveloper: 'Ayarlar',
			runConnectionClosed: 'BaÄŸlantÄ± kapalÄ±',
			runConnectionConnecting: 'BaÄŸlanÄ±yor',
			runConnectionOpen: 'HazÄ±r',
			send: 'GÃ¶nder',
			sending: 'GÃ¶nderiliyor...',
			submitConnectionConnecting: 'BaÄŸlantÄ± kuruluyor...',
			submitConnectionWaiting: 'BaÄŸlantÄ± bekleniyor',
			submitInProgress: 'Ã‡alÄ±ÅŸma sÃ¼rÃ¼yor...',
		},
		developer: {
			apiKey: 'API anahtarÄ±',
			configDescription: 'Bu ayarlar canlÄ± sohbet hattÄ±nÄ± besler.',
			configHeading: 'Ã‡alÄ±ÅŸma hattÄ± ayarlarÄ±',
			currentDefaults: 'Mevcut varsayÄ±lanlar',
			description: 'GeliÅŸtirici ayarlarÄ±, ham ileti gÃ¶rÃ¼nÃ¼rlÃ¼ÄŸÃ¼ ve tanÄ±lama araÃ§larÄ±.',
			heading: 'GeliÅŸtirici',
			includePresentationBlocks: 'Sunum bloklarÄ±nÄ± iste',
			lastError: 'Son Ã§alÄ±ÅŸma hatasÄ±',
			model: 'Model',
			noMessages: 'HenÃ¼z ileti yok.',
			provider: 'SaÄŸlayÄ±cÄ±',
			rawTransport: 'Ham iletiler',
			refreshAuthContext: 'GiriÅŸ durumunu yenile',
			showTransport: 'Ä°letileri gÃ¶ster',
			hideTransport: 'Ä°letileri gizle',
			localOnlyNote: 'Bu ayarlar yalnÄ±z bu tarayÄ±cÄ±da saklanÄ±r.',
			clearLocalToken: 'KaydÄ± temizle',
			scope: 'Kapsam',
			claims: 'Oturum iddialarÄ±',
			userMetadata: 'KullanÄ±cÄ± verisi',
			troubleshooting: 'TanÄ±lama',
		},
		run: {
			approvalBoundary: 'Onay noktasÄ±',
			currentRunProgress: 'Ã‡alÄ±ÅŸma durumu',
			currentSurfaceContext: 'BaÄŸlam',
			observedSteps: 'Son adÄ±mlar',
			runtimePhases: 'Ã‡alÄ±ÅŸma adÄ±mlarÄ±',
			showingLatestSteps: 'Son {count} adÄ±m',
			pastRuns: 'GeÃ§miÅŸ Ã§alÄ±ÅŸmalar',
			pastRunsCollapsed: 'GeÃ§miÅŸ Ã§alÄ±ÅŸmalara daha sonra geri dÃ¶nebilirsin.',
			surfaceHeading: 'Sohbet akÄ±ÅŸÄ±',
			surfaceSubtitle: 'Runa cevabÄ± ve onay isteyen adÄ±mlar sÄ±rayla ilerler.',
		},
		runtime: {
			apiKeyRequired: 'API anahtarÄ± gerekli.',
			connectionOpening: 'CanlÄ± baÄŸlantÄ± henÃ¼z kuruluyor. Biraz bekleyip tekrar dene.',
			connectionUnavailable:
				'CanlÄ± baÄŸlantÄ± henÃ¼z hazÄ±r deÄŸil. Ä°stek gÃ¶ndermeden Ã¶nce yeniden baÄŸlanmasÄ±nÄ± bekle.',
			modelRequired: 'Model gerekli.',
			promptRequired: 'Ä°stek metni gerekli.',
			unsupportedWsMessage: 'Desteklenmeyen WebSocket sunucu mesajÄ±.',
			wsClosedRetrying: 'CanlÄ± baÄŸlantÄ± kapandÄ±. Yeniden deneniyor...',
			wsFailedRetrying: 'WebSocket baÄŸlantÄ±sÄ± baÅŸarÄ±sÄ±z oldu. Yeniden deneniyor...',
			wsNotOpen: 'WebSocket aÃ§Ä±k deÄŸil.',
			wsParsingUnknown: 'Bilinmeyen WebSocket mesaj Ã§Ã¶zÃ¼mleme hatasÄ±.',
			unknownApprovalSubmit: 'Bilinmeyen onay gÃ¶nderim hatasÄ±.',
			unknownInspectionSubmit: 'Bilinmeyen detay isteÄŸi gÃ¶nderim hatasÄ±.',
			unknownSubmit: 'Bilinmeyen gÃ¶nderim hatasÄ±.',
		},
	},
} as const;

const defaultCopy = copyByLocale[defaultLocale];

export const uiCopy = {
	...defaultCopy,
	account: {
		...defaultCopy.account,
		description: 'Profilini, oturumunu ve tercihlerini yÃ¶net.',
	},
	approval: {
		...defaultCopy.approval,
		action: 'Ä°ÅŸlem',
		callId: 'Ä°stek kimliÄŸi',
		details: 'AyrÄ±ntÄ±lar',
		note: 'Not',
		pendingEmphasis: 'Runa devam etmeden Ã¶nce kararÄ±nÄ± bekliyor.',
		tool: 'AraÃ§',
	},
	appShell: {
		...defaultCopy.appShell,
		accountSubtitle: 'Profilini ve tercihlerini yÃ¶net.',
		chatSubtitle: 'Ä°ÅŸi sohbet iÃ§inde ilerlet.',
		devicesSubtitle: 'BaÄŸlÄ± bilgisayarlarÄ±nÄ± ve izin verdiÄŸin yetenekleri yÃ¶net.',
		historySubtitle: 'Eski sohbetlere ve yarÄ±m kalan iÅŸlere dÃ¶n.',
	},
	auth: {
		...defaultCopy.auth,
		connecting: 'GiriÅŸ hazÄ±rlanÄ±yor',
		loginDescription: 'E-posta ve ÅŸifre ile giriÅŸ yap.',
		oauthDescription: 'Google veya GitHub ile devam edebilirsin.',
		statusAnonymous: 'GiriÅŸ yap',
		statusBootstrapping: 'GiriÅŸ hazÄ±rlanÄ±yor',
		subtitle: 'Projeni bilen sakin bir Ã§alÄ±ÅŸma ortaÄŸÄ±na giriÅŸ yap.',
	},
	chat: {
		...defaultCopy.chat,
		configMissing: 'Sohbet ÅŸu anda hazÄ±r deÄŸil. Biraz sonra yeniden deneyebilirsin.',
		emptySurface: 'HazÄ±rsan ilk mesajÄ± yaz; Runa iÅŸi adÄ±m adÄ±m toparlasÄ±n.',
		heroSubtitle: 'Ä°ÅŸi sohbet iÃ§inde ilerlet; onay gereken adÄ±mlarda karar sende kalÄ±r.',
		heroTitle: 'Ã‡alÄ±ÅŸma ortaÄŸÄ±n',
		openDeveloper: 'Ayarlar',
		submitInProgress: 'Ã‡alÄ±ÅŸma sÃ¼rÃ¼yor...',
	},
	advancedView: {
		heading: 'GeliÅŸmiÅŸ gÃ¶rÃ¼nÃ¼m',
		description: 'GeliÅŸtirici sayfasÄ±nÄ± gÃ¶rÃ¼nÃ¼r kÄ±lar, normal kullanÄ±m akÄ±ÅŸÄ±nÄ± deÄŸiÅŸtirmez.',
	},
	run: {
		...defaultCopy.run,
		pastRunsCollapsed: 'GeÃ§miÅŸ Ã§alÄ±ÅŸmalara daha sonra geri dÃ¶nebilirsin.',
		surfaceHeading: 'Sohbet akÄ±ÅŸÄ±',
		surfaceSubtitle: 'Runa cevabÄ± ve onay isteyen adÄ±mlar sÄ±rayla ilerler.',
	},
} as const;
