export type SupportedLocale = 'en' | 'tr';

export const defaultLocale: SupportedLocale = 'tr';

const copyByLocale = {
	en: {
		account: {
			authErrorTitle: 'Account issue',
			clearLocalToken: 'Clear local token',
			description: 'Profile, basic session details, and sign-out stay here.',
			heading: 'Account',
			logout: 'Sign out',
			profileSection: 'Account summary',
			refreshAuthContext: 'Refresh account state',
		},
		approval: {
			action: 'Action',
			approve: 'Approve',
			approved: 'Approved',
			callId: 'Call id',
			cancelled: 'Cancelled',
			details: 'Technical details',
			expired: 'Expired',
			note: 'Note',
			pending: 'Pending approval',
			pendingEmphasis: 'Runa paused here and is waiting for your decision before continuing.',
			reject: 'Reject',
			rejected: 'Rejected',
			tool: 'Tool',
		},
		appNav: {
			accountDescription: 'Profile, session, and sign-out.',
			accountLabel: 'Account',
			chatDescription: 'Conversation, current run, and approvals.',
			chatLabel: 'Chat',
			devicesDescription: 'Connected desktop companions.',
			devicesLabel: 'Devices',
			developerLabel: 'Developer Mode',
			historyDescription: 'Saved conversations and shared work.',
			historyLabel: 'History',
			navLabel: 'Authenticated app navigation',
		},
		appShell: {
			authenticatedSession: 'Authenticated session',
			chatEyebrow: 'work companion',
			chatSubtitle: 'The main surface is the chat workspace.',
			chatTitle: 'Chat workspace',
			developerEyebrow: 'second layer',
			developerSubtitle: 'Developer-only configuration and debug visibility live here.',
			developerTitle: 'Developer Mode',
			devicesEyebrow: 'connected devices',
			devicesSubtitle:
				'Desktop companion presence and allowed capabilities live in their own space.',
			devicesTitle: 'Devices',
			historyEyebrow: 'work history',
			historySubtitle: 'Past conversations stay searchable without crowding the main chat.',
			historyTitle: 'History',
			serviceSession: 'Service session',
			accountEyebrow: 'account',
			accountSubtitle: 'Only the essential account and session controls stay here.',
			accountTitle: 'Account',
		},
		auth: {
			authenticatedShellNotice:
				'A successful sign-in opens the authenticated workspace immediately.',
			bearerTokenRequired: 'Bearer token is required.',
			bootstrapDescription:
				'The app checks auth state on load, reads OAuth redirect tokens, and decides whether to open login or the authenticated workspace.',
			bootstrapTitle: 'Current browser auth state',
			clearStoredToken: 'Clear stored token',
			clearStoredTokenNotice:
				'The stored bearer token was cleared only in this browser tab. A remote session may still remain active until the current access token expires.',
			connecting: 'Checking account state',
			continueWithGithub: 'Continue with GitHub',
			continueWithGoogle: 'Continue with Google',
			devSession: 'Start local dev session',
			email: 'Email address',
			invalidSession: 'Bearer token did not resolve to an authenticated session.',
			localDevOnly: 'Local dev auth bootstrap can only start in the browser.',
			login: 'Sign in',
			loginAction: 'Sign in',
			loginDescription: 'Sign in with your email and password.',
			loginPending: 'Signing in...',
			logoutRemoteWarning:
				'Local browser state was cleared, but the remote session may remain active until the current access token expires.',
			modeLabel: 'Authentication mode',
			noStoredToken: 'No stored token in this tab',
			oauthDescription:
				'This starts a real OAuth flow. The app reads the returned token during auth bootstrap.',
			oauthRedirecting: 'Redirecting to the OAuth provider...',
			oauthValidating: 'OAuth returned to the app. Validating the session now.',
			password: 'Password',
			passwordPlaceholderLogin: 'Enter your password',
			passwordPlaceholderSignup: 'Create a strong password',
			profileDeferred: 'Account management remains intentionally lightweight in this sprint.',
			refreshAuthContext: 'Refresh auth state',
			signup: 'Create account',
			signupAction: 'Create account',
			signupDescription: 'Create an account with email and password.',
			signupPending: 'Creating account...',
			signupVerificationNote:
				'If email confirmation is enabled, the app stays on the login surface and shows the verification message.',
			startingDevSession: 'Starting a local dev auth session...',
			statusAnonymous: 'Anonymous',
			statusBootstrapping: 'Checking auth context',
			storedToken: 'Stored token in this tab',
			subtitle: 'Runa opens first as a simple work companion. Technical auth seams stay secondary.',
			title: 'Continue with Runa',
			token: 'Token',
			tokenAction: 'Validate token',
			tokenDescription: 'Validate an existing bearer token.',
			tokenFallbackNote:
				'The token path stays available as a fallback for existing sessions and troubleshooting.',
			tokenPending: 'Validating...',
			tokenPlaceholder: 'Paste a bearer token',
			unresolvedPrincipal: 'Unresolved',
		},
		chat: {
			composerPlaceholder: 'Write what you want to get done...',
			configMissing:
				'Chat is ready, but runtime configuration is incomplete. Open Developer Mode and enter a valid API key before sending a request.',
			currentRunHeading: 'Current work',
			emptySurface:
				'No visible work yet. Send a message to start and see the current work surface here.',
			heroSubtitle:
				'Conversation, approvals, and the live work surface stay together here. Technical controls live in Developer Mode.',
			heroTitle: 'Your work companion',
			openDeveloper: 'Open Developer Mode',
			runConnectionClosed: 'Connection closed',
			runConnectionConnecting: 'Connecting',
			runConnectionOpen: 'Live',
			send: 'Send',
			sending: 'Sending...',
			submitConnectionConnecting: 'Connecting...',
			submitConnectionWaiting: 'Waiting for live connection',
			submitInProgress: 'Working...',
		},
		developer: {
			apiKey: 'API key',
			configDescription:
				'These settings feed the live chat runtime but stay out of the main chat surface.',
			configHeading: 'Runtime configuration',
			currentDefaults: 'Current defaults',
			description:
				'Developer-only runtime controls, raw transport visibility, and troubleshooting live here.',
			heading: 'Developer Mode',
			includePresentationBlocks: 'Request presentation blocks',
			lastError: 'Latest runtime error',
			model: 'Model',
			noMessages: 'No transport messages yet.',
			provider: 'Provider',
			rawTransport: 'Raw transport',
			refreshAuthContext: 'Refresh auth state',
			showTransport: 'Show transport',
			hideTransport: 'Hide transport',
			localOnlyNote: 'These settings are local to this browser and exist for dev or operator use.',
			clearLocalToken: 'Clear local token',
			scope: 'Scope',
			claims: 'Claims',
			userMetadata: 'User metadata',
			troubleshooting: 'Troubleshooting',
		},
		run: {
			approvalBoundary: 'Approval boundary',
			currentRunProgress: 'Current work',
			currentSurfaceContext: 'Context',
			observedSteps: 'Recent steps',
			runtimePhases: 'Work phases',
			showingLatestSteps: 'Showing latest {count} steps',
			pastRuns: 'Recent work',
			pastRunsCollapsed: 'Recent work stays available without crowding the main conversation.',
			surfaceHeading: 'Current work surface',
			surfaceSubtitle: 'The latest summaries and details stay here while the work continues.',
		},
		runtime: {
			apiKeyRequired: 'API key is required.',
			connectionOpening: 'Live connection is still opening. Wait a moment and try again.',
			connectionUnavailable:
				'Live connection is not ready yet. Wait for reconnection before sending a request.',
			modelRequired: 'Model is required.',
			promptRequired: 'Prompt is required.',
			unsupportedWsMessage: 'Unsupported WebSocket server message.',
			wsClosedRetrying: 'Live connection closed. Retrying...',
			wsFailedRetrying: 'WebSocket connection failed. Retrying...',
			wsNotOpen: 'WebSocket is not open.',
			wsParsingUnknown: 'Unknown WebSocket message parsing error.',
			unknownApprovalSubmit: 'Unknown approval resolve submit error.',
			unknownInspectionSubmit: 'Unknown inspection request submit error.',
			unknownSubmit: 'Unknown submit error.',
		},
	},
	tr: {
		account: {
			authErrorTitle: 'Hesap sorunu',
			clearLocalToken: 'Yerel tokeni temizle',
			description: 'Profil, temel oturum bilgileri ve çıkış burada kalır.',
			heading: 'Hesap',
			logout: 'Çıkış yap',
			profileSection: 'Hesap özeti',
			refreshAuthContext: 'Hesap durumunu yenile',
		},
		approval: {
			action: 'İşlem',
			approve: 'Kabul Et',
			approved: 'Kabul edildi',
			callId: 'Çağrı kimliği',
			cancelled: 'İptal edildi',
			details: 'Teknik detaylar',
			expired: 'Süresi doldu',
			note: 'Not',
			pending: 'Onay bekliyor',
			pendingEmphasis: 'Runa burada durdu ve devam etmeden önce senin kararını bekliyor.',
			reject: 'Reddet',
			rejected: 'Reddedildi',
			tool: 'Araç',
		},
		appNav: {
			accountDescription: 'Profil, oturum ve çıkış.',
			accountLabel: 'Hesap',
			chatDescription: 'Sohbet, mevcut çalışma ve onaylar.',
			chatLabel: 'Sohbet',
			devicesDescription: 'Bagli masaustu companionlar.',
			devicesLabel: 'Cihazlar',
			developerLabel: 'Developer Mode',
			historyDescription: 'Kayitli sohbetler ve paylasilan isler.',
			historyLabel: 'Gecmis',
			navLabel: 'Kimlik dogrulanmis uygulama gezintisi',
		},
		appShell: {
			authenticatedSession: 'Kimliği doğrulanmış oturum',
			chatEyebrow: 'çalışma ortağı',
			chatSubtitle: 'Ana yüz sohbet akışı ve çalışma alanı olarak kurulur.',
			chatTitle: 'Çalışma alanı',
			developerEyebrow: 'ikinci katman',
			developerSubtitle: 'Yalnız geliştiriciye ait ayarlar ve teknik görünürlük burada tutulur.',
			developerTitle: 'Developer Mode',
			devicesEyebrow: 'bagli cihazlar',
			devicesSubtitle: 'Masaustu companion durumu ve izinli yetenekler kendi alaninda kalir.',
			devicesTitle: 'Cihazlar',
			historyEyebrow: 'calisma gecmisi',
			historySubtitle: 'Gecmis sohbetler ana sohbeti kalabaliklastirmadan aranabilir kalir.',
			historyTitle: 'Gecmis',
			serviceSession: 'Servis oturumu',
			accountEyebrow: 'hesap',
			accountSubtitle: 'Sadece gerekli hesap ve oturum kontrolleri burada kalır.',
			accountTitle: 'Hesap',
		},
		auth: {
			authenticatedShellNotice:
				'Başarılı giriş seni doğrudan kimliği doğrulanmış çalışma alanına alır.',
			bearerTokenRequired: 'Bearer token gerekli.',
			bootstrapDescription:
				'Uygulama açılırken auth durumunu kontrol eder, OAuth dönüş tokenini okur ve giriş mi yoksa çalışma alanı mı gösterileceğine karar verir.',
			bootstrapTitle: 'Mevcut tarayıcı auth durumu',
			clearStoredToken: 'Kayıtlı tokeni temizle',
			clearStoredTokenNotice:
				'Kayıtlı bearer token sadece bu tarayıcı sekmesinden temizlendi. Uzak oturum, mevcut access token süresi dolana kadar aktif kalabilir.',
			connecting: 'Hesap durumu kontrol ediliyor',
			continueWithGithub: 'GitHub ile devam et',
			continueWithGoogle: 'Google ile devam et',
			devSession: 'Local dev oturumu başlat',
			email: 'E-posta adresi',
			invalidSession: 'Bearer token geçerli bir oturuma dönüşmedi.',
			localDevOnly: 'Local dev auth bootstrap sadece tarayıcıda başlayabilir.',
			login: 'Giriş',
			loginAction: 'Giriş yap',
			loginDescription: 'E-posta ve şifre ile giriş yap.',
			loginPending: 'Giriş yapılıyor...',
			logoutRemoteWarning:
				'Yerel tarayıcı durumu temizlendi, ancak uzak oturum mevcut access token süresi dolana kadar aktif kalabilir.',
			modeLabel: 'Kimlik doğrulama modu',
			noStoredToken: 'Bu sekmede kayıtlı token yok',
			oauthDescription:
				'Bu, gerçek bir OAuth başlangıç akışıdır. Uygulama geri dönen tokeni auth bootstrap sırasında okur.',
			oauthRedirecting: 'OAuth sağlayıcısına yönlendiriliyor...',
			oauthValidating: 'OAuth ile geri dönüldü. Oturum doğrulanıyor.',
			password: 'Şifre',
			passwordPlaceholderLogin: 'Şifreni gir',
			passwordPlaceholderSignup: 'Güçlü bir şifre oluştur',
			profileDeferred: 'Hesap yönetimi bu sprintte bilinçli olarak hafif tutuldu.',
			refreshAuthContext: 'Auth durumunu yenile',
			signup: 'Kayıt ol',
			signupAction: 'Hesap oluştur',
			signupDescription: 'E-posta ve şifre ile hesap oluştur.',
			signupPending: 'Hesap oluşturuluyor...',
			signupVerificationNote:
				'E-posta doğrulaması açıksa uygulama giriş ekranında kalır ve doğrulama mesajını gösterir.',
			startingDevSession: 'Local dev auth oturumu başlatılıyor...',
			statusAnonymous: 'Anonim',
			statusBootstrapping: 'Auth bağlamı kontrol ediliyor',
			storedToken: 'Bu sekmede kayıtlı token var',
			subtitle:
				'Runa önce sade bir çalışma ortağı gibi açılır. Teknik auth yüzeyleri ikinci planda kalır.',
			title: 'Runa ile devam et',
			token: 'Token',
			tokenAction: 'Tokeni doğrula',
			tokenDescription: 'Var olan bir bearer tokeni doğrula.',
			tokenFallbackNote:
				'Token yolu, mevcut oturumlar ve troubleshooting için güvenli bir yedek olarak kalır.',
			tokenPending: 'Doğrulanıyor...',
			tokenPlaceholder: 'Bearer token yapıştır',
			unresolvedPrincipal: 'Çözülmedi',
		},
		chat: {
			composerPlaceholder: 'Ne yapmak istediğini yaz...',
			configMissing:
				'Sohbet hazır ama runtime kurulumu eksik. İstek göndermeden önce Developer Mode içinden geçerli bir API anahtarı gir.',
			currentRunHeading: 'Mevcut çalışma',
			emptySurface:
				'Henüz görünür bir çalışma yok. Yeni bir mesaj gönderdiğinde mevcut çalışma yüzeyi burada görünür.',
			heroSubtitle:
				'Sohbet, onaylar ve canlı çalışma yüzeyi burada birlikte kalır. Teknik kontroller Developer Mode içindedir.',
			heroTitle: 'Çalışma ortağın',
			openDeveloper: 'Developer Mode ac',
			runConnectionClosed: 'Baglanti kapali',
			runConnectionConnecting: 'Baglaniyor',
			runConnectionOpen: 'Canli',
			send: 'Gonder',
			sending: 'Gonderiliyor...',
			submitConnectionConnecting: 'Canli baglanti kuruluyor...',
			submitConnectionWaiting: 'Canli baglanti bekleniyor',
			submitInProgress: 'Çalışma sürüyor...',
		},
		developer: {
			apiKey: 'API anahtarı',
			configDescription:
				'Bu ayarlar canlı sohbet runtimeini besler ama ana sohbet yüzeyinde görünmez.',
			configHeading: 'Runtime ayarları',
			currentDefaults: 'Mevcut varsayılanlar',
			description:
				'Yalnız geliştiriciye ait runtime ayarları, ham transport görünürlüğü ve troubleshooting burada tutulur.',
			heading: 'Developer Mode',
			includePresentationBlocks: 'Presentation block iste',
			lastError: 'Son runtime hatası',
			model: 'Model',
			noMessages: 'Henüz transport mesajı yok.',
			provider: 'Sağlayıcı',
			rawTransport: 'Ham transport',
			refreshAuthContext: 'Auth durumunu yenile',
			showTransport: 'Transportu göster',
			hideTransport: 'Transportu gizle',
			localOnlyNote: 'Bu ayarlar sadece bu tarayıcıda tutulur ve dev/operator kullanımına aittir.',
			clearLocalToken: 'Yerel tokeni temizle',
			scope: 'Scope',
			claims: 'Claims',
			userMetadata: 'Kullanıcı metadata',
			troubleshooting: 'Troubleshooting',
		},
		run: {
			approvalBoundary: 'Onay siniri',
			currentRunProgress: 'Calisma durumu',
			currentSurfaceContext: 'Baglam',
			observedSteps: 'Son adimlar',
			runtimePhases: 'Calisma asamalari',
			showingLatestSteps: 'Son {count} adim gosteriliyor',
			pastRuns: 'Gecmis calismalar',
			pastRunsCollapsed: 'Gecmis calismalar ana sohbeti kalabaliklastirmadan burada kalir.',
			surfaceHeading: 'Mevcut çalışma yüzeyi',
			surfaceSubtitle: 'En yeni özet kartları ve bağlı detaylar çalışma sürerken burada kalır.',
		},
		runtime: {
			apiKeyRequired: 'API anahtarı gerekli.',
			connectionOpening: 'Canlı bağlantı henüz kuruluyor. Biraz bekleyip tekrar dene.',
			connectionUnavailable:
				'Canlı bağlantı henüz hazır değil. İstek göndermeden önce yeniden bağlanmasını bekle.',
			modelRequired: 'Model gerekli.',
			promptRequired: 'İstek metni gerekli.',
			unsupportedWsMessage: 'Desteklenmeyen WebSocket sunucu mesajı.',
			wsClosedRetrying: 'Canlı bağlantı kapandı. Yeniden deneniyor...',
			wsFailedRetrying: 'WebSocket bağlantısı başarısız oldu. Yeniden deneniyor...',
			wsNotOpen: 'WebSocket açık değil.',
			wsParsingUnknown: 'Bilinmeyen WebSocket mesaj çözümleme hatası.',
			unknownApprovalSubmit: 'Bilinmeyen onay gönderim hatası.',
			unknownInspectionSubmit: 'Bilinmeyen detay isteği gönderim hatası.',
			unknownSubmit: 'Bilinmeyen gönderim hatası.',
		},
	},
} as const;

const defaultCopy = copyByLocale[defaultLocale];

export const uiCopy = {
	...defaultCopy,
	chat: {
		...defaultCopy.chat,
		emptySurface:
			'Henuz gorunur bir calisma yok. Yeni bir mesaj gonderdiginde mevcut calisma yuzeyi burada gorunur.',
		heroSubtitle:
			'Sohbet, onaylar ve canli calisma yuzeyi burada birlikte kalir. Teknik kontroller Developer Mode icindedir.',
		heroTitle: 'Calisma ortagin',
		submitInProgress: 'Calisma suruyor...',
	},
	run: {
		...defaultCopy.run,
		surfaceHeading: 'Mevcut calisma yuzeyi',
		surfaceSubtitle: 'En yeni ozetler ve bagli detaylar calisma surerken burada kalir.',
	},
} as const;
