export type {
	ApprovalResolveClientMessage,
	ApprovalResolveDecision,
	ApprovalResolvePayload,
	ConnectionReadyServerMessage,
	GatewayProvider,
	GatewayProviderConfig,
	InspectionDetailBlock,
	InspectionDetailItem,
	InspectionDetailLevel,
	InspectionRequestClientMessage,
	InspectionRequestPayload,
	InspectionTargetKind,
	ModelAttachment,
	PresentationBlocksServerMessage,
	RenderBlock,
	RunAcceptedServerMessage,
	RunFinishedServerMessage,
	RunRejectedServerMessage,
	RunRequestClientMessage,
	RunRequestModelRequest,
	RunRequestPayload,
	RuntimeEventServerMessage,
	TextDeltaDiscardServerMessage,
	UploadAttachmentResponse,
	WebSocketServerBridgeMessage,
	WebSocketClientMessage,
	WebSocketServerMessage,
} from '@runa/types';

export type ConnectionStatus = 'closed' | 'connecting' | 'error' | 'open';
